### 배당금 등록
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker" : "MMM"
}

### 회사 조회
GET http://localhost:8080/company
Accept: application/json

### 자동 완성 검색
GET http://localhost:8080/company/autocomplete?keyword=n
Accept: application/json
