spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"

